// content script actions
export const CHECK_IF_CONTAINS_REGULAR_OFFER = 'CHECK_IF_CONTAINS_REGULAR_OFFER';
export const SCROLL_TO_REGULAR_OFFER = 'SCROLL_TO_REGULAR_OFFER';
export const GO_TO_URL = 'GO_TO_URL';

// content scripts responses
export const PAGE_LOADED = 'PAGE_LOADED';
export const DOES_NOT_CONTAINS_ANY_OFFERS = 'DOES_NOT_CONTAINS_ANY_OFFERS';
export const CONTAINS_REGULAR_OFFERS = 'CONTAINS_REGULAR_OFFERS';
export const DOES_NOT_CONTAINS_REGULAR_OFFERS = 'DOES_NOT_CONTAINS_REGULAR_OFFERS';

// others
export const REQUEST_CONTENT_SCRIPT = 'REQUEST_CONTENT_SCRIPT';
export const LOOKUP_REGULAR_OFFERS = 'LOOKUP_REGULAR_OFFERS';
export const LOOKUP_CANCEL = 'LOOKUP_CANCEL';
export const ERROR = 'ERROR';
export const SCANNING = 'SCANNING';
export const FOUND = 'FOUND';
export const NOT_FOUND = 'NOT_FOUND';
export const FOUND_ON_CURRENT_PAGE = 'FOUND_ON_CURRENT_PAGE';
